### ISSUE TITLE
How to run decode and encode alongside Inference on Flex 140 gpu using Itex

### ISSUE THREAD

**Issue by sagi-scalers-ai** [intel/intel-extension-for-tensorflow#45]
I'm seeking guidance on incorporating decode and encode processes alongside inference on Flex 140 GPUs using ITEX? as well as implementing parallel streams of inference on the same GPU. Any assistance on these aspects would be greatly appreciated.

**Comment by huiyan2021** [comment]
@sagi-scalers-ai We have published a Video Streamer workflow on Intel CPU, is this what you want to do on Flex 140 GPU?

**Comment by huiyan2021** [comment]
https://github.com/intel/video-streamer/blob/main/DEVCATALOG.md

**Comment by xiguiw** [comment]
@sagi-scalers-ai 
'To run decode and encode alongside Inference on Flex 140 gpu using ITEX', we had  a solution.
The whole pipeline is based on Gstreamer.
There is Gstreamer decode/encode plugin (run on GPU), and implemente inference as gstreamer plugin  as @huiyan2021 pointed the [video-streamer](https://github.com/intel/video-streamer/blob/main/DEVCATALOG.md).

1. To [decode/encode on GPU](https://gitlab.freedesktop.org/gstreamer/gstreamer),  you want to build gstreamer from source code with vaapi enabled. There is no binary released (due to licenses problem).
2. To implemente a gstreamer ITEX Inference plugin, you can refere to [video-streamer](https://github.com/intel/video-streamer/blob/main/DEVCATALOG.md).
3. Also, you need `vacompositor` to combine multiple video stream into one batch for inference to support multple video streams.

We are trying to upstream the code into [video-streamer](https://github.com/intel/video-streamer/blob/main/DEVCATALOG.md) repo.

**Comment by sagi-scalers-ai** [comment]
@xiguiw Thank you for your response.
