### ISSUE TITLE
FusedBatchMatMul precedence over FusedMatMul

### ISSUE THREAD

**Issue by SriAlavandar** [intel/intel-extension-for-tensorflow#62]
I am running Hugging Face OPT 350M model with ITEX 2.14

As part of Intermediate block, when Relu/Gelu Fusion is being triggered I noticed that resultant op type is of FusedBatchMatMul instead of FusedMatMul (where postops would be Gelu Approximate/Exact/Relu).

**Input Graph:**

![image](https://github.com/intel/intel-extension-for-tensorflow/assets/40352419/0a66b361-7a3d-4edf-917b-22b871b96ace)

**Resultant Graph:**

![image](https://github.com/intel/intel-extension-for-tensorflow/assets/40352419/c6621241-c960-4bd4-be95-e6d4d5c3af71)

Attaching the reference where Graph level Fusion is being taken place for this - https://github.com/intel/intel-extension-for-tensorflow/blob/d8fe3daa49f81767c1dd783325c330a145d945bd/itex/core/graph/remapper/remapper.cc#L912 

Any specific reason why FusedBatchMatMul precedence is chosen over FusedMatMul?

**Comment by jianyizh** [comment]
In older version of keras, they use tensordot to implement [dense layers](https://github.com/keras-team/keras/blob/r2.14/keras/layers/core/dense.py#L244C23-L244C35). For tensors with rank > 3, it will do the reshape and use MatMul, i.e. [a,b,c] -> reshape [a\*b,c] -> matmul [a\*b,d] -> reshape [a,b,d] -> bias -> activation. We use BMM so that we do not need the reshape op. It's also easier to deal with other post ops in future. I think current keras 3.0 also uses BMM.
