### ISSUE TITLE
Will there be any acceleration for intel core i-series processors?

### ISSUE THREAD

**Issue by ghsanti** [intel/intel-extension-for-tensorflow#77]
For example this ones: https://www.intel.com/content/www/us/en/products/details/processors/core/i7.html

From what I read in the docs it's only Xeon processors and some GPUs supported. 

Is there anything available for core i-series that I missed ?

**Comment by wangkl2** [comment]
As mentioned in the [ITEX release note](https://github.com/intel/intel-extension-for-tensorflow/releases/tag/v2.15.0.1), it officially supports Intel Data Center CPUs (`Xeon`) and Intel Data Center `Max` and `Flex` GPUs, as well as experimentally supporting `Arc-A` Client dGPUs. And these are the target hardware this project currently optimizes and validates on. 

As for `Core I-series CPU`, the built wheels of ITEX CPU does support and utilize various ISAs including AVX2, AVX512 and AMX. So it technically supports `Core i-series CPU` in functionality, which providing AVX2 ISA. But when it comes to the acceleration of this library on `Core i-series CPU`, it should be quite limited, since lots of optimization passes have been upstream by Intel developers or WIP upstreaming to Official TensorFlow, as a result, the performance boost of using this library can be expected as limited, especially on relatively low-end CPU ISA such as AVX2. 

If you still want to run AI workloads on Core i-series CPU, please try both ITEX and Official TensorFlow.

**Comment by ghsanti** [comment]
Interesting, thank you, I did, and didn't notice any speed ups. I think tensorflow CPU is compiled to handle AVX2 already, but I could be wrong.

Your answer is very much appreciated though !
